### ISSUE TITLE
Fail after save field

### ISSUE THREAD

**Issue by gisu** [benjamminf/craft-neo#10]
I wanted to test. Build a Simple Neo Field with two Blocks not more. Click on Save than a CException

/craft/app/framework/db/ar/CActiveRecord.php(146)
```
 */
public function __get($name)
{
    if(isset($this->_attributes[$name]))
        return $this->_attributes[$name];
    elseif(isset($this->getMetaData()->columns[$name]))
        return null;
    elseif(isset($this->_related[$name]))
        return $this->_related[$name];
    elseif(isset($this->getMetaData()->relations[$name]))
        return $this->getRelated($name);
    else
        return parent::__get($name); => Error
}
/**
 * PHP setter magic method.
 * This method is overridden so that AR attributes can be accessed like properties.
 * @param string $name property name
 * @param mixed $value property value
 */
public function __set($name,$value)
{
    if($this->setAttribute($name,$value)===false)
    {
```

Tested with Craft 2.6.2781

**Comment by benjamminf** [comment]
Hey @gisu thanks for the report. Can I get some more details on how you encountered this issue? What fields/field types did your blocks contain? And what were your block type settings? Thanks, Ben.

**Comment by gisu** [comment]
First Try with two Blocks and serveral Fields (Exception).

Than a second try super simple. Two blocks only, one top level, the second block is nested - fields are empty.

![image](https://cloud.githubusercontent.com/assets/442468/14851747/330178a0-0c82-11e6-8842-2943f1db7862.png)

**Comment by gisu** [comment]
I make a new Test with a new Craft Installation, it works. So i think on the first tested Installation is something broken or it comes from a other Plugin.

**Comment by benjamminf** [comment]
Ah okay, thanks for the heads up. Am I able to get a list of the plugins you were using alongside Neo? I still want to see if I can reproduce this error to make sure I'm not doing anything wrong. Thanks!

**Comment by gisu** [comment]
I have added the Plugins from the Live Page to the Test Installation. Works. So i think its a bug inside the Core or a Datatable in the DB is broken (maybe from a Update, Deinstallation Plugin whatever).

**Comment by benjamminf** [comment]
Hmm okay then, if you have this problem again reply here and I'll reopen the issue.
