### ISSUE TITLE
Fixed bug where Neo could be created inside Matrix

### ISSUE THREAD

**Issue by SilverCrowS** [benjamminf/craft-neo#101]
this is not a bug actually it worked just fine with me , it was more efficient, after the last Update i noticed that all my neo blocks inside matrix was removed, any way that this bug return ? :)

**Comment by benjamminf** [comment]
Sorry about that, Neo was never meant to be used inside Matrix. It's definitely possible it may have worked for you, but it's a very fragile setup and none of the plugin's architecture was designed to account for those situations, and more complex setups would undoubtedly break for you.

Unfortunately your only solutions are to either downgrade to the last version that had this "feature", or redesign your content architecture without this arrangement.
