### ISSUE TITLE
Getting PHP Error

### ISSUE THREAD

**Issue by brianrivet** [benjamminf/craft-neo#102]
Hi,

I'm just updated my Craft install to v.2.6.2974 and I am now getting a PHP error whenever I try to edit an entry that has a Neo field in it. The error says it is trying to get property of non-object. The line number it gives is line 749 in NeoFieldType.php. Can you help me to resolve this issue? I can provide login credentials if needed.

Thanks!

Brian

**Comment by benjamminf** [comment]
The offending line: https://github.com/benjamminf/craft-neo/blob/master/neo/fieldtypes/NeoFieldType.php#L749

My guess is that one of your Neo blocks contains a field that's field type no longer exists. Are you using any third-party field type plugins?

**Comment by brianrivet** [comment]
Hi Benjamin,

First thanks for getting back to me so quickly. I really appreciate it. That was the culprit. I had removed a couple of plugins I wasn’t using and forgot to remove one of them from the Neo field set.


Thanks,

Brian Rivet
brian@odysseydesignstudio.com
Phone: 225-505-9243
Fax: 225-300-8517
www.odysseydesignstudio.com
