### ISSUE TITLE
Managing Neo field on the frontend

### ISSUE THREAD

**Issue by Moorst** [benjamminf/craft-neo#107]
I was just wondering whether there is any documentation on how to manage Neo fields on the frontend?
 I'm planning to use Neo for some user profile fields and they'd need the ability to manage them from their frontend account page.

**Comment by benjamminf** [comment]
That's a pretty interesting problem. It shouldn't be too hard – you'll want to open up your DOM inspect tools in the CP when looking at a Neo field to reference how the input fields are formatted/named. You can ignore the `modified` and `collapsed` hidden fields on each block, but you'll want to replicate all the other hidden fields. Apart from the additional `level` field, it's the same process as [managing a Matrix field from the front-end](https://craftcms.stackexchange.com/questions/1318/how-to-get-matrix-editor-into-frontend?noredirect=1&lq=1).
