### ISSUE TITLE
Child block gets added to wrong parent

### ISSUE THREAD

**Issue by benjamminf** [benjamminf/craft-neo#11]
1. Add two root level blocks
2. In the first root level block, add a new child block
3. In that new child block, try adding a child block. It will add it to the last block instead.

**Comment by shornuk** [comment]
Hi, 
Just started using Neo. Great plugin btw. I am seeing this too. Any timescale for a fix? Thanks!

**Comment by benjamminf** [comment]
@shornuk Wow, what a coincidence. I literally JUST fixed this about 12 seconds ago. Expect it in the next release (will be released over the weekend).

**Comment by shornuk** [comment]
Awesome! Thanks for that!
