### ISSUE TITLE
Craft 3

### ISSUE THREAD

**Issue by optima-ben** [benjamminf/craft-neo#113]
Hi Ben, 

Hope you are well, brilliant addon by the way. Thank you for the time and effort you've put into it. A quick question:  Is Neo ready for Craft 3 and if not do you have any intentions of supporting it? We are hoping to use your field on all ongoing developments so need to make sure you are happy to continue to support it. Many thanks again.

Kind regards,
Ben

**Comment by benjamminf** [comment]
Hey Ben. Neo will support Craft 3. You can follow the development of the plugin under the `dev-3` branch. It's a complete rewrite so it's going to take a while yet before something usable is ready. But the plan is still to be ready by Craft 3's first release.

**Comment by optima-ben** [comment]
Perfect thank you.

**Comment by fThues** [comment]
Are things still on track for the rewrite to be released alongside Craft 3? I appreciate this is a huge undertaking and I'm not trying to be pushy, it's just that we're starting a new project and I'm evaluating whether to build on Craft 2 or 3. Your plugin's availability is a big factor in that decision. Thanks!

**Comment by knynkwl** [comment]
Any update on this?

**Comment by brianrivet** [comment]
Hi Ben,
Thanks for the plugin, it really is great. I was hoping to see if there is any new ETA on when the Craft 3 version might be ready. I have a few projects that I could really use Neo on.

Thanks!
