### ISSUE TITLE
individual color for each block type

### ISSUE THREAD

**Issue by waswebb** [benjamminf/craft-neo#115]
Hi

First of all: You build a awesome Plugin, I hove it, thank you for that great plugin!

I often have a lot of different block types and my cliends use a lot of blocks on every page. 
That can become very cliends. So I think it would be nice to have the option do give every blocktype a color like this:

<img width="880" alt="bildschirmfoto 2017-09-20 um 10 49 08" src="https://user-images.githubusercontent.com/21307389/30635235-175863f4-9df2-11e7-8d8c-01bcf73927de.png">

**Comment by AbbeyDesign** [comment]
+10 for this. I can do it, painfully, via the cp css plugin but it would be much more functional if it where something I could just click when creating the field. Also would like the whole box colored (subtle) instead of just the outlines in the above example.

**Comment by benjamminf** [comment]
Thanks @waswebb! This is a planned feature for the Craft 3 rewrite, but sadly it won't be developed for the Craft 2 version. @AbbeyDesign I think I'm just going to go with the title bar + border like above as nesting blocks with clashing colours looks bad, but we'll see.
