### ISSUE TITLE
Block Tabs

### ISSUE THREAD

**Issue by superflausch** [benjamminf/craft-neo#12]
First thanks again for your work and an awesome plugin. While playing around with it I noticed two small points:

- The block tab titles (when you create multiple tabs for a block) don't get translated

- The block tabs trigger also the checkbox to select the block

**Comment by benjamminf** [comment]
Thanks for the report! I'll fix these up hopefully tonight.

**Comment by benjamminf** [comment]
I can't seem to reproduce the first issue. They are being translated just fine on my end.

**Comment by benjamminf** [comment]
Block tabs triggering the checkbox has been fixed in the latest release. Translations are working for me, so maybe I inadvertently fixed it while changing something else. I'm closing this issue for now, but if you're still having issues post here and I'll reopen it.
