### ISSUE TITLE
Documentation With Templating Examples

### ISSUE THREAD

**Issue by aenrii** [benjamminf/craft-neo#13]
Thanks for a brilliant plugin!

Would love to eventually see some documentation with examples of templating and so forth. Various basic use cases perhaps.

**Comment by benjamminf** [comment]
Cheers 👍 

Absolutely, It's something I'm working on. For the most part it should work the same as Matrix fields. I'm working on having the template API be the same as entries in structures, so at the moment there's not a whole lot of support for handling child blocks. Fun fact though, you can use the `{% nav %}` tag to output a Neo field.

**Comment by smockensturm** [comment]
re: Templating. How do we get to, loop through and render the child blocks?

**Comment by smockensturm** [comment]
Right. If we use block.children we get ALL the children regardless of entry.

**Comment by smockensturm** [comment]
Here we go:

```
{% for block in entry.neoContentBlocks  %}
    {% if block.type == 'multiColumn' %}
	{% for col in block.children.ownerId(entry.id).type('column') %}
		...
	{% endfor %}
    {% endif %}
{% endfor %}
```

where "multiColumn" is the parent and 'column' the children.

**Comment by benjamminf** [comment]
Hey @smockensturm sorry this has been trouble for you. Frustratingly this feature has been pretty hard to implement, but I've held back from advertising this plugin and writing the docs until it's implemented.

I've just released `1.0.2` which will let you get child blocks in the template, using a temporary API, just so it's usable in the meantime. This temporary API will remain supported throughout the `1.x` version. You can now check the README on how to use Neo in your templates.

**Comment by smockensturm** [comment]
Fantastic! Works a charm. On behalf of our entire team, we thank you. Looking forward to what you get up to.

**Comment by benjamminf** [comment]
My pleasure, thanks for using the plugin!
