### ISSUE TITLE
1.1.1 Install Triggers Manual Update and Database Error

### ISSUE THREAD

**Issue by smockensturm** [benjamminf/craft-neo#26]
Craft 2.6.2789

- Dropped a brand new Neo folder into Plugins on an existing install.
- Got the message:  "To complete the Neo update, some changes must be made to your database." 
- Clicked "Finish Up"
- Works for a little while, backs up database, then "Rolling back.."
- ERROR: "Craft was unable to install this update :( The site has been restored to the state it was in before the attempted update. There was a problem updating your database."

What do you think this could be all about?

This is in the URL. Why?
../admin/manualupdate/neo

**Comment by benjamminf** [comment]
Hey Steve, thanks for reporting this. As you're probably aware, `1.1.1` has had a few issues so I've taken it down until I've resolved them. Though it's strange to see a failed update, considering the migration is only two lines long (just adds a column to a table in the DB).

Can you search your Craft logs (In the CP footer, click "Server Info", then "Logs") for the following messages, and let me know if either of them show up?

- Adding column ownerLocale to table neoblockstructures
- Adding foreign key to neoblockstructures

**Comment by smockensturm** [comment]
I found the second string in the logs. But not the first string.

For clarity: I wouldn't call it a failed update. That was an attempt at a new install of 1.1.1 to an existing system. (With several Matrix blocks already set up and populated.) That's why I was curious about "manualupdate" in the url.

**Comment by benjamminf** [comment]
Oh okay, so this is happening when you first install Neo version `1.1.1`? That seems very odd that it would immediately trigger an update. Once I fix the other issue with upgrading to `1.1.1` I'll look into this one.

**Comment by benjamminf** [comment]
I'm looking through the source of Craft's plugin service, and from what I can tell the only way a plugin update is triggered is if there exists some record of the plugin in the DB prior (in the `craft_plugins` table). Can you check to confirm this is or isn't the case?

**Comment by smockensturm** [comment]
Yes. It is the case. And it's curious. Could it be left over from the first time the install bombed?

Can I safely remove some tables and records as if to say Neo never existed here?

**Comment by benjamminf** [comment]
It's possible, though Craft should've reverted the DB transaction completely. Unless inserting into the plugins table is a part of a different transaction.

You should be able to safely delete the row for the Neo plugin from the `craft_plugins` table. Also, remove the following tables entirely if they exist: `craft_neoblocks`, `craft_neoblockstructures`, `craft_neoblocktypes`, and `craft_neogroups`. I've done this a few times for when plugins go haywire. Of course just to be safe, do a full DB export before you do this.

**Comment by benjamminf** [comment]
Just following up on this issue. Did you manage to get the plugin installed?

**Comment by smockensturm** [comment]
Sure. We did have to delete the Neo row from `craft_plugins` Installed 1.2.1 without issue after clearing the database.

Not sure how we got out of sync. But all is well. Thanks again.

**Comment by benjamminf** [comment]
That's good to hear. It was likely remnants from that past failed installation. Thanks for the update :+1:
