### ISSUE TITLE
Select all (cmd + a) in handle Field does not work (Mac OS X Chrome)

### ISSUE THREAD

**Issue by christianruhstaller** [benjamminf/craft-neo#29]
This is a small issue but still a small usability thing and annoyed me a little bit.

When creating a BlockType and you want to change the handle, Cmd + A should select the whole input value, but it directly gets unselected again.

Tested in Chrome 50.0.2661.102.

**Comment by benjamminf** [comment]
Ah yeah, I see what you mean. Should be relatively easy to fix. I'll make sure it's done for the next release.
