### ISSUE TITLE
Drafts not saving any fields

### ISSUE THREAD

**Issue by tyler-deboer** [benjamminf/craft-neo#35]
When I'm creating/updating/editing entries in Draft mode, none of the fields in my Neo field are updating, including Rich Text, Plain Text, Assets, Dropdowns, etc. This _only_ happens on Draft mode though, and _only_ when I save a Draft. Live Preview is working fine on Draft mode (all my additions/edits are showing up as expected), however when I save the Draft and the entry edit page refreshes, all of the changes I made on my fields are wiped away.

This issue doesn't happen (my changes do save and carry over when the entry edit page is refreshed) if I'm in Draft mode, enter in my changes/additions in the fields, and then Publish my draft. The new live published version of the entry has the changes I made to it when I was editing the Draft. It also doesn't happen on edits to published entries or even disabled published entries - every time I save those, the changes I make in the fields don't get wiped away. It seems to only happen on Draft saves.

I'm seeing the issue on dev, staging, and production environments, so I don't suspect it's a server issue.

**Comment by benjamminf** [comment]
Hey Tyler, thanks for the report. Bit busy today but I'll look into this ASAP.

**Comment by tyler-deboer** [comment]
No worries, thanks Benjamin! Love the plugin...it's been working wonders for our semi-complex content builder that the Matrix+Super Table combo wasn't quite suited for.

**Comment by benjamminf** [comment]
Cheers mate :+1: Finally had a bit of time to test this and yes I'm seeing the same issue.

**Comment by benjamminf** [comment]
Alright, I know what's going on. This bug was introduced in Neo 1.3.0 where blocks are now cached. Entry drafts are not busting the cache for blocks. Just need to add a rule in there for them and it should be all sorted. Will have this fixed and released today.

**Comment by tyler-deboer** [comment]
Just downloaded the newest version and tried adding a Draft to an existing entry on my dev environment. When I saved it, nothing loaded and I get an error:

`Fatal error: Call to a member function getTimestamp() on null in /[my/path/to/directory]/craft/plugins/neo/etc/Neo_BlockCacheDependency.php on line 36`

Would this be something to do with the fact I'm in a dev environment?

**Comment by benjamminf** [comment]
No, there's still a bug present that I didn't catch. After a while of playing around with it, I've determined the best solution is to just remove caching. I couldn't reliably invalidate the cache with drafts. Now I know why they say the two hardest things in CS is naming things and cache invalidation...

Anyway, sorry about this. I'm releasing another fix in a few minutes. Hang tight.

**Comment by tyler-deboer** [comment]
No need to apologize! I appreciate your help on this and thanks again for digging into this.

**Comment by tyler-deboer** [comment]
I hate to keep bugging you about this, because this has been such a helpful plugin for our team and I don't want to be a pain. I'm still having issues with Drafts -- it seems like my initial problem (where fields weren't updating when I saved something in Draft mode) was solved, but now I'm having troubles with something that _was_ working before.

So like I said, it seems that changes made in Draft mode do save correctly when you click Save Draft. However, when I Publish a draft, changes aren't carrying over to the existing, original entry. 

So say I have an entry with a few column blocks that have some content and layout settings. If I change some of the settings and content and hit Save as Draft, it correctly carries over the edits to the Draft. However, if I then hit Publish Draft on the new Draft page, those changes _don't_ get carried over or updated on the existing entry -- so the old, original entry is still the exact same. I'm wondering if maybe the fixes to the Draft stuff overwrote or messed the functionality of publishing a draft and overwriting the original content?

Hopefully this makes sense, and if there's no obvious or easy solution to this, there are some work arounds I'm sure we can come up with. I appreciate your help on this!

**Comment by benjamminf** [comment]
Hey Tyler, thanks for the detailed write-up. Sorry it's not working! I'm away for the next few days so I won't be able to verify and fix it until I'm back. You say it was working? What version did you last notice it working in?

**Comment by benjamminf** [comment]
Okay fixed this... again. This time it had to do with the modification checking script. Blocks only save if they're modified, but due to the way drafts were being stored in the DB it wasn't working correctly. Fixed now, will be available in the next release.

**Comment by benjamminf** [comment]
I finally published that release ([1.3.4](https://github.com/benjamminf/craft-neo/releases/tag/1.3.4)), apologies for the unnecessarily long delay!

**Comment by tyler-deboer** [comment]
No worries mate, thanks again for your help on this!
