### ISSUE TITLE
Matrix Block Dropdown Groups

### ISSUE THREAD

**Issue by simplethemes** [benjamminf/craft-neo#37]
First of all, thanks for this great plugin. I was using PMM, but ultimately Neo suited my specific needs. One thing I miss that I'd like to request is dropdown groups:

![dropdown groups](https://s3.amazonaws.com/f.cl.ly/items/371s3X3h0q2k472P1V3M/Image%202016-07-11%20at%2010.12.29%20PM.jpg)

I was thinking this could be a managed somewhat like so:
![concept_ui]
(https://s3.amazonaws.com/f.cl.ly/items/2L2l1O2t0H3F0c0h1q1q/Image%202016-07-11%20at%2010.23.05%20PM.png)

Thanks again for all your hard work on this!

**Comment by simplethemes** [comment]
Well crap! I just realized this is already possible via the "Group" button. I thought it was disabled because of the color. You're awesome!

**Comment by benjamminf** [comment]
Haha no worries man, cheers. Maybe I should change the colour of that text...
