### ISSUE TITLE
Content summary in collapsed block title

### ISSUE THREAD

**Issue by benjamminf** [benjamminf/craft-neo#4]
Just like with Matrix blocks, having the field values summarised in the block title when collapsed would be nice.

**Comment by benjamminf** [comment]
I'm a bit on the fence about implementing this now that I've used Neo in production for a while. I actually like collapsed blocks without it's content filling up the title bar. It keeps it clean and readable.

**Comment by roydigerhund** [comment]
Actually I love this feature in the Matrix blocks. Sometimes you have a lot of blocks on a page and it's much easier to spot the right one with those small summaries.

**Comment by ockam** [comment]
+1. At least the first field.

**Comment by benjamminf** [comment]
I actually started writing the feature in the other day. Decided to improve on how Matrix does it a little. For example, asset fields will show a small thumbnail in the title bar. Will be ready for the next release.

**Comment by benjamminf** [comment]
Now implemented in 1.4.0 which is currently still in testing. If you're interested you can grab the early release from the master branch.
