### ISSUE TITLE
Limit child blocks applies to all parent blocks

### ISSUE THREAD

**Issue by admench** [benjamminf/craft-neo#40]
I have a **columns** block which has _column_ child blocks that are limited to a maximum of 4.

In the scenario I currently face, I have added 1 **columns** block with 4 (the maximum) child _column_ blocks.
If I add another top-level **columns** block, it already imposes the limit on adding more children (by graying out the button to add a _column_).

**Comment by benjamminf** [comment]
Hey @admench, yeah this behaviour is expected. I realise limiting block type counts per parent is more useful but I thought that kind of behaviour was not inline with what the setting described. There's also cases where you want to limit block types across the entire field too.

It's been suggested that there should be a "Max child blocks" setting per block type, but there's also a lot of other rule options that would be equally as useful. I don't want to pollute block types with many settings, but this one comes up a lot so I'll definitely add it in at some point soon.

**Comment by admench** [comment]
Thanks for the explanation - I can give instructions to the content editor
for now, which is a workaround that I can manage easily. Great work with
the plugin thank you.

**Comment by benjamminf** [comment]
Now implemented in 1.4.0 which is currently still in testing. If you're interested you can grab the early release from the master branch.

**Comment by admench** [comment]
Thanks Ben!

**Comment by admench** [comment]
Hi Ben,

I have upgraded to 1.4.1 which still exhibits the same issue, is this deliberate, did you stick to your thoughts that it is better to limit the number of child block types for the entire entry rather than per-parent?

Thanks again

**Comment by admench** [comment]
Sorry, Ignore my last comment, I just noticed the new 'Max Child Blocks' field.

Thanks for your continued work on this!
