### ISSUE TITLE
Rich Text fields not initialising

### ISSUE THREAD

**Issue by tomwelch** [benjamminf/craft-neo#44]
I've noticed that Rich Text fields are not initialising within Neo. When a block is added with a Rich Text field inside, a JS error is thrown and the Redactor field is not loaded.

`Uncaught TypeError: Cannot read property 'opts' of undefined`

![Rich Text field failing to load](https://cloud.githubusercontent.com/assets/1016558/17477115/3ce29e1a-5d5b-11e6-9155-571c16d66ad3.png)

I believe this is related to the following:

	/*<![CDATA[*/
	$.extend($.Redactor.opts.langs["en"], {
		"fullscreen": "Fullscreen",
		"insert-page-break": "Insert Page Break",
		"table": "Table",
		"insert-table": "Insert table",
		"insert-row-above": "Insert row above",
		"insert-row-below": "Insert row below",
		"insert-column-left": "Insert column left",
		"insert-column-right": "Insert column right",
		"add-head": "Add head",
		"delete-head": "Delete head",
		"delete-column": "Delete column",
		"delete-row": "Delete row",
		"delete-table": "Delete table",
		"video": "Video",
		"video-html-code": "Video Embed Code or Youtube\/Vimeo Link"
	});
	new Craft.RichTextInput({
		"id": "fields-blogBody-new0-fields-text",
		"linkOptions": [{
			"optionTitle": "Link to an entry",
			"elementType": "Entry",
			"sources": ["singles", "section:3", "section:2"]
		}],
		"assetSources": [],
		"transforms": [],
		"elementLocale": "en_gb",
		"redactorConfig": {
			"buttons": ["format", "bold", "italic", "lists", "link", "file", "horizontalrule"],
			"plugins": ["source", "fullscreen"]
		},
		"redactorLang": "en"
	});
	/*]]>*/

It's possible to trick the fields into working, if a Rich Text field is added to the section outside of Neo, for example:

![Tricking the Rich Text field into loading](https://cloud.githubusercontent.com/assets/1016558/17476967/7cfc413c-5d5a-11e6-86c1-4dd7c8b0a906.png)

I'm currently using Neo 1.3.3 in a fresh install of Craft 2.6.2903. I've not installed any other plugins and created all the fields from scratch.

If there's anything else I can give you to help, please let me know.

Thanks in advance,

Tom.

**Comment by benjamminf** [comment]
Hey Tom, thanks for the detailed report! From what you've provided, it's clear the Redactor JS library is not available at the time of creating the text block. Blocks load their resources on the fly, so it might be an issue in a couple of specific areas. I haven't been able to reproduce it (yet) but I'll look into it hopefully tonight.

**Comment by tomwelch** [comment]
Hi Benjamin. No worries at all. If it helps I can zip you my installation with a database dump. It's completely fresh so no trouble.

**Comment by benjamminf** [comment]
Hey Tom, I've released 1.3.4 which *might* address this issue. I've changed the way Neo loads resources for blocks, and I think it'll solve this issue. I can't be sure as I couldn't replicate it, but give the new version a try and let me know how it goes :+1:

**Comment by benjamminf** [comment]
Hey @tomwelch any updates on the situation? Cheers, Ben.

**Comment by tomwelch** [comment]
Hi Benjamin. Sorry for being slow getting back to you. I think that's fixed it! The rich text fields are now working as expected.

When creating Rich Text fields for testing I tend to leave the Config option as Default. I wonder if this might have been causing the problem as a specific config wasn't chosen. I'm going to go back a version and try it out tonight for my curiosity, I'll let you know.

Look forward to putting Neo to work on a project now!

Cheers.

**Comment by benjamminf** [comment]
No worries Tom, glad it's fixed it for you!

I'm honestly not sure what the problem was, but I don't think it was the settings on the field. My best guess was some sort of race condition where the Redactor library was loaded after the field was initialised.
