### ISSUE TITLE
How to Output the Children on a Block

### ISSUE THREAD

**Issue by waswebb** [benjamminf/craft-neo#47]
Hi

I'm new in Craft. How can i output the children of a block?

With this code a don't get a output for the children. Sorry if my code looks nooby, i'm a craft beginner.
```twig
{% for block in entry.body.level(1) %}
    {% switch block.type.handle %}

        {% case 'boxContentImage' %}
        	{{ block.richText }}
		        	
        	{% for item in block.children %}
				{{ block.something }}
            {% endfor %}
			
		{% case .. %}

    {% endswitch %}
{% endfor %}
```

**Comment by benjamminf** [comment]
That's alright, everyone starts somewhere :)

Your inner for loop on the blocks children uses the variable `item`, but you're still using the variable `block` inside the loop. You need to change `block.something` to `item.something`.
