### ISSUE TITLE
Question: Craft 3 plans

### ISSUE THREAD

**Issue by tomdavies** [benjamminf/craft-neo#49]
Hey Ben, do you currently plan to port Neo to Craft 3 (in due course)?

I understand that Neo is a hobby project and that you can't commit to anything definitively, but Craft 3 is getting close enough that we need to make sure there's an upgrade path for our client sites, and that means thinking carefully about potentially plugin use, especially those that are both fairly substantial and OS, so I wondered if can give any guide at the moment?

Thanks for your time!

**Comment by benjamminf** [comment]
Hey Tom. Neo absolutely will be ported to Craft 3 :+1: I'm waiting until 3 has a more stable API until I start on it though.

You might be interested to know #17 is coming out in the next release, so there'll be a downgrade path in place shortly as well.

**Comment by tomdavies** [comment]
Great to hear. Thanks for the quick reply. Might be worth adding to the FAQ perhaps?

**Comment by benjamminf** [comment]
Sure, I can add it in there :)

**Comment by benjamminf** [comment]
Ask and ye shall receive https://github.com/benjamminf/craft-neo/wiki/6.-FAQ#will-neo-support-craft-3

**Comment by Etsur** [comment]
Now that the beta has been released, is this something we can expect soon?

**Comment by benjamminf** [comment]
I wouldn't say soon, but I'll be starting on the port in the next few weeks. Plan is to have it complete by Craft 3's release in 6-9 months. I'd like to have it done some time before then but we'll see – this is a big plugin that relies heavily on the elements API, which has been completely overhauled in 3.

**Comment by SimonEast** [comment]
Ben, are there any aspects of Craft 3 support that others can assist with? Perhaps if it was broken down into smaller chunks some of us might be able to chip in with contributions.

**Comment by Harrisonbro** [comment]
I echo Simon: if there's any way we can chip in to help with the Craft 3 update please let us know!

**Comment by benjamminf** [comment]
@SimonEast @Harrisonbro I haven't really thought about how to make it easy for contributors, but it's probably a good idea to set up the Kanban board in the Projects section. It's a little early in development for me to start accepting contributions yet—I'm still figuring out how I want the code architecture to look, and I need to set up some more tooling (PHP unit tests, linter, etc.)—but once that's all done I'd love some help!

**Comment by Harrisonbro** [comment]
Ok. Let us know when we can help!

**Comment by kisonay** [comment]
We are just about a month away from GA. Let us know if there is anything we can do to help.
