### ISSUE TITLE
Internal Server Error - `admin/actions/neo/saveExpansion`

### ISSUE THREAD

**Issue by radarseven** [benjamminf/craft-neo#54]
Seeing the error below in a multi-locale site error when attempting to expand/collapse Neo blocks. Note: This is only occurring in the locales other than the primary locale, in this case, English. As a result, expanded/collapsed state isn't being saved with the entry. Any ideas?

`Argument 1 passed to Craft\NeoService::saveBlockCollapse() must be an instance of 
Craft\Neo&#95;BlockModel, instance of stdClass given, called in -redacted-/plugins/_src/craft-neo/neo/controllers/NeoController.php on line 26.`

**Comment by benjamminf** [comment]
I'm seeing this issue too. Thanks for the report, I'll look into it as soon as possible.
