### ISSUE TITLE
Issues when changing a Neo field's translation setting

### ISSUE THREAD

**Issue by benjamminf** [benjamminf/craft-neo#55]
If a Neo field has content, changing it's translation setting causes strange side-effects with the existing content. This is due to the locales not updating correctly and consistently across all related data. Need to correct the `NeoService::_applyFieldTranslationSetting()` method to either copy the structures along with the blocks (if going from non-translated to translated) or just not duplicate the blocks into the other locales. It also seems that the locales aren't updating for the primary site locale blocks, instead remaining `NULL`.

**Comment by superflausch** [comment]
We also noticed that the content of our NEO field within an entry didn't populate the newly added locales as the other translatable fields do. I quickly checked our DB and also noticed the NULL values you mentioned.

**Comment by davidhellmann** [comment]
Any news about this topic? We run into it now and it's sadly a big problem :/

**Comment by slimiles** [comment]
Seems to work in Neo Version 1.3.3; I got two language and it has no `NULL` in de database. (Craft CMS 2.6.2911)

**Comment by benjamminf** [comment]
Good news, I finally have this fixed and working on the dev branch. Expect this very soon 👍
