### ISSUE TITLE
Have I reached the limit of Neo?

### ISSUE THREAD

**Issue by shealan** [benjamminf/craft-neo#56]
I've been building a reasonably complex Neo layout.

![screenshot](https://photos-3.dropbox.com/t/2/AAAJs_a3vRDApglDgI0Le33WzVYwYfdIk5PhvLgkBVvcYQ/12/6296508/png/32x32/3/1478491200/0/2/Screenshot%202016-11-06%2023.37.25.png/EOCT2QQYnuoVIAcoBw/ejNUIu_bwEKhyL_eWhEdxnnC-m2J-Ryzc2S5h6RWg7o?size_mode=3&dl=0&size=2048x1536)

When constructing the page I seem to have hit a wall. It will only save content up until a certain row. If I try to add another (to this admittedly long page) I get a couldn't save error. When I look for the problem field the last row is empty (which is the stated error).

![screenshot](https://photos-2.dropbox.com/t/2/AADcCGKYH-Qa79oXZiMhi8M-z0311uucjrkesyY9_65T_Q/12/6296508/png/32x32/3/1478491200/0/2/Screenshot%202016-11-06%2023.43.25.png/EOCT2QQYn-oVIAcoBw/E0xJazdAxuKxQhIBJd31yVcmCOqaMD3G8aBF7OMQYcQ?size_mode=3&dl=0&size=2048x1536)

I can't see any errors in the console or debugger.

**Comment by benjamminf** [comment]
This sounds awfully a lot like you're hitting your PHP post variable limit. [Have a look at this issue](http://craftcms.stackexchange.com/questions/2765/matrix-field-input-error-from-within-the-control-panel/2777#2777) and see if increasing your max post vars setting solves it.

**Comment by benjamminf** [comment]
I also notice you're using 1.4.0. It hasn't officially been released yet as I'm still testing it on real-world projects and noticed a couple of bugs. Don't worry though, they're rather edge case and not related to saving content (it's performance related, and an issue with Neo-to-Matrix conversion with locales).

**Comment by shealan** [comment]
Oooh thanks for the pointer... I'm going to edit my php.ini and see if it helps... Will get back to you.

**Comment by shealan** [comment]
That fixed it. Can't thank you enough for the pointer (and the incredible plugin).

**Comment by benjamminf** [comment]
Awesome! No worries, thanks for using Neo 😄
