### ISSUE TITLE
Visual Error on Neo 1.4.0

### ISSUE THREAD

**Issue by theskyfloor** [benjamminf/craft-neo#57]
Getting this crazy CSS error on my content admin pages with Neo 1.4

![screen shot 2016-11-07 at 8 05 07 am](https://cloud.githubusercontent.com/assets/8887839/20060489/ffc0c8f6-a4c0-11e6-8d3b-4ff7007a2280.png)

**Comment by benjamminf** [comment]
What browser are you using? I think I know what's going on.

**Comment by theskyfloor** [comment]
Safari 10

**Comment by benjamminf** [comment]
Haha gotta love Safari. It really is the IE of modern web development. Was a simple fix though.
