### ISSUE TITLE
Live Preview not updating [v1.4.0]

### ISSUE THREAD

**Issue by richhayler** [benjamminf/craft-neo#59]
If I use the following code live preview works as expected:

`{% for item in entry.items.level(1) %}`

However if I try to order the display of the items and use the following code live preview is not updated with any changes to my items or their content.

`{% for item in entry.items.level(1).order('date asc') %}`

Seeing this in Craft CMS **v2.6.2950**

**Comment by benjamminf** [comment]
Yes this is expected – the `order` filter is not explicitly part of the API for Neo's criteria model, so it has not been supported for Live Preview. Unfortunately I also don't plan to.
