### ISSUE TITLE
Version rollback not working 

### ISSUE THREAD

**Issue by sidneywidmer** [benjamminf/craft-neo#63]
The `$modified` attribute on the `Neo_BlockModel` prevents a successful rollback to an older version. 

For example if you just change the title of an entry and save it, all the $modified attributes on the BlockModels are false because nothing got changed. This setting is also json encoded and saved in the entryversions table. When we later try to rollback to this version, all the neo blocks get skipped because in the logic we think they where not modified...

**Comment by sidneywidmer** [comment]
By the way, I just saw that the same issue happens with entrydrafts since they're also json encoded

**Comment by websNL** [comment]
Hi,

I have the same problem with version rollback. In an entry there are some blocks that got changed and are live.

When I go back to an older version and click on the _Revert entry to this version_ button. The blocks are still the same as in the live and not those of the version I choose.

Would be very happy if this got fixed.

**Comment by benjamminf** [comment]
I've actually had this fixed for a while now, not sure why I didn't respond here. I'm sure if you clone the master branch this should be all working now.

**Comment by websNL** [comment]
Geachte relatie,

Welkom bij de servicedesk van Webs. Voor vragen, bugs en wijzigingen aan uw
website of hosting pakket, kunt u gebruik maken van dit Servicedesk
systeem.

Nadat een project of service is opgeleverd zijn er vaak nog veel
aanvullende vragen. Om efficiënt antwoord te kunnen geven op deze vragen
werken we met de Webs Servicedesk. Jij kunt met een eigen account 24-uur
per dag al je vragen en wensen insturen. Doordat je deze instuurt via de
Servicedesk kunnen wij aan onze kant deze vragen efficiënt oppakken door
ze direct bij de juiste mensen neer te leggen. 

*De voordelen van de Webs Servicedesk*
- 24/7 bereikbaar
- Vragen worden sneller opgepakt en beantwoord 
- Inzage in de status van je vraag

*Hoe maak je gebruik van de Webs Servicedesk?*
Voordat je gebruik kunt maken van de Servicedesk is het belangrijk om eerst
even je account te activeren. Dit kun je doen via deze link:
https://websnl.teamwork.com/support/#resetpassword/282461:f88040ea-4072-4866-8590-9760cebb4040:281148.
Nadat je account is geactiveerd kun je gebruik maken van deze dienst door
een e-mail met je vragen te sturen naar support@webs.nl
<mailto:support@webs.nl> of via de website
https://websnl.teamwork.com/support.

Met vriendelijke groet,

Servicedesk medewerkers van Webs
040 2324611
support@webs.nl <mailto:support@webs.nl>
