### ISSUE TITLE
Error when non-admin user tries to expand/collapse neo blocks.

### ISSUE THREAD

**Issue by imagehat** [benjamminf/craft-neo#67]
When logged in as a non-admin user, expanding or collapsing a neo block results in flash error showing on the page that states "An unknown error occurred."

In the console it appears this is because the ajax request to the controller action is unauthorized.

```
POST [urlremoved]/index.php/admin/actions/neo/saveExpansion 403 (forbidden)
```

This does not happen when logged in as a full admin user.

Any ideas? This add-on is great but we turned a new site over to a client and now they're seeing this error and I can't seem to find any permission settings to change.

_Edited to add version numbers:_
Neo 1.4.0
Craft 2.6.2952

![screenshot 2016-12-14 17 32 17](https://cloud.githubusercontent.com/assets/68237/21205803/d3a6f9b8-c223-11e6-807c-1f209a4ad238.png)

![screenshot 2016-12-14 17 33 18](https://cloud.githubusercontent.com/assets/68237/21205804/d3ab25a6-c223-11e6-8448-23c8b3f93149.png)

**Comment by imagehat** [comment]
Quick followup, I found the issue and wonder if it is intentional (and if so, if it really should be).

In `controllers/NeoController.php` the `actionSaveExpansion()` function is calling the BaseController method to check for an admin user. Shouldn't a non-admin user with access to the entry in the control panel be able to expand/collapse a block?

```
	public function actionSaveExpansion()
	{
		$this->requireAdmin();
		$this->requireAjaxRequest();
		$this->requirePostRequest();
```

It's also set for `actionRenderBlocks()`. I would think an editor should be able to duplicate a block as well.

Thanks for your attention. And again, this add-on is amazing, thanks for all of your hard work!

**Comment by benjamminf** [comment]
Sorry for the late response @imagehat – you're right, I mistakenly added those `requireAdmin` calls. I've gone ahead and taken them out, so it should be all good now if you download from the master branch.

Thanks for the kind words, glad you like the plugin :)

**Comment by SimonEast** [comment]
Just noticed those `requireAdmin()` calls gone. Should it still check for a privileged user of some sort? Otherwise could that AJAX endpoint potentially be used to retrieve the contents of a Neo block that is not meant for public viewing?

**Comment by benjamminf** [comment]
@SimonEast Controllers automatically are restricted to logged in users, but yes I realise there's still the privilege concern with general user accounts. Thankfully, the only two non-admin controller actions are `actionSaveExpansion` and `actionRenderBlocks`, neither of which actually expose any content data. `actionSaveExpansion` might be a concern since it writes to the database, but it's extremely limited and pretty harmless. Still, I'd like to replace that with some JS local storage magic, but it's pretty low on the priority list right now.
