### ISSUE TITLE
Matrix rows not respecting re-order in Neo field

### ISSUE THREAD

**Issue by jonXmack** [benjamminf/craft-neo#69]
Hi, I have just noticed an issue when there's a Matrix field within a Neo field. Despite being able to drag and drop the matrix rows within the Neo field, when saving the entry, the order reverts back to how it was initially published. I have just updated Neo to the latest version to ensure it wasn't an issue with using an older version but the issue is still present.

**Comment by simplethemes** [comment]
Same issue here. Is this possibly related to a recent Craft update or has this just flown under the radar?

**Comment by benjamminf** [comment]
This is actually an issue with the Garnish framework that Craft uses. I'm using a form data diffing function in Garnish that is buggy. I'm replacing it with my own. Will update when done.

**Comment by simplethemes** [comment]
Thank you for the quick response.

**Comment by benjamminf** [comment]
@simplethemes download from the master branch – should be all working now
