### ISSUE TITLE
NEO not saving block when submitted

### ISSUE THREAD

**Issue by brianrivet** [benjamminf/craft-neo#71]
Hi,

I'm having a bit of trouble with Neo. I have set up a number of block types and I have a page where I have a bunch of blocks set up. I have a group of page row blocks, then a sub items of those I have some grid column blocks. Inside the grid column blocks I have blocks for content elements. On the last page row of my entry, I have two grid columns set up, and when I try to create content elements blocks inside of that grid column, it lets me create them and fill out the fields, but if I submit the entry to save it, when I come back it hasn't saved any of the content elements in that last grid column. I also tried deleting the grid column block and then creating it again and adding content to it. When /I deleted it, and then recreated it, it created the block, but it isn't letting me update the values of any of the fields to change what they were when the block was initially created.

Now to add another level of difficulty to this, it only seems to be happening on my local development server for now. I deployed the site to a stage server so you could access it to see what the problem might be, but for some reason it isn't happening on the remote server, only on my local. I am running MAMP 4.0.6, and php 5.5.38, with craft v. 2.6.2958 and Neo v. 1.3.5

**Comment by benjamminf** [comment]
Hey @brianrivet, to me this seems like the PHP `max_input_vars` and/or `post_max_size` settings are too low on your local server ([see link](http://craftcms.stackexchange.com/questions/2765/matrix-field-input-error-from-within-the-control-panel/2777#2777)). Try increasing these values and see if that fixes it.

**Comment by brianrivet** [comment]
Hi Benjamin,

Thanks for getting back to me so quickly. I took your recommendations and that appears to have fixed the issue. Thanks for your help!




Brian Rivet
brian@odysseydesignstudio.com
Phone: 225-505-9243
Fax: 225-300-8517
www.odysseydesignstudio.com
