### ISSUE TITLE
All relabelled fields get reset when validation fails

### ISSUE THREAD

**Issue by SimonEast** [benjamminf/craft-neo#73]
*Brilliant plugin by the way. It's becoming part of our essential toolkit!*

But today I've noticed a bug where I lose all custom field labels (from relabel plugin) when the form fails validation.

Steps to reproduce:

1. Create/Edit a Neo field with multiple blocks
2. Relabel some fields (using great relabel plugin)
3. Do something to cause a validation error such as leave a handle blank
4. Hit save
5. **ALL fields that were previously relabelled have now been reset to default (lost their custom labels)**

Using Neo 1.4.0 and Relabel 0.1.3.

I couldn't seem to replicate the bug when relabelling a standard field, so I think the bug might be in Neo, not in Relabel.

Can anyone confirm if this bug also happens for them, and where we might look to start fixing it?

Simon.

**Comment by benjamminf** [comment]
Hey Simon, thanks!

Seems like this is an issue with Relabel, as it won't keep them around if an error is reported. I'll move this issue over to the Relabel repository.
