### ISSUE TITLE
Saving entry doesn't update some fields, reverts back 

### ISSUE THREAD

**Issue by owldesign** [benjamminf/craft-neo#75]
Hey @benjamminf awsome plugin and I appreciate all the work put into it! 👍 

Check out the gif bellow, I'm noticing that fields don't get updated and keep reverting to previous record.

Steps I take:
1. Remove old text from field, hit update entry, field reverted back to old 
2. Update any other field in the block and also the desired field, now both fields get saved just fine
3. Revert any other field in the block to previous content and also update the desired field, both fields get saved just fine
4. Updating desired filed again stops works and keeps reverted to the previous record

Figured before I start digging through the plugin code, maybe you understand what might be happening or suggest some troubleshooting steps?

But here is a fun fact (seems to hold up for now). I noticed the updating issue only happens when I hit `⌘S` keyboard shortcut, however manually clicking `Save and continue editing` on the entry, updates all the fields as expected.. 😕 Almost feels like keyboard shortcut save is the root issue here, can you verify?

![kap-capture](https://cloud.githubusercontent.com/assets/438764/22052945/8f27c37c-dd02-11e6-907e-bd6c784d8630.gif)

Thanks again @benjamminf

**Comment by zachshallbetter** [comment]
We discovered this issue yesterday as well. We found that we HAD to delete the recreate the entry entirely to solve the issue.

**Comment by jake-dohm** [comment]
We've just run into this problem ourselves also.

Once you've created some content blocks and filled them in, and saved the entry, then when you return to the page and edit the content of that block, it doesn't updated in the CP, DB, or front-end (obviously).

Then, the only way to "update" the data in that block is to copy the content from it, delete it, add a new block, paste back in the content, and then update it.

Some more data:
- It isn't consistently broken. Most of the time the data **doesn't** save, but sometimes it will.
- I tested both using the `⌘S` shortcut and the button (because @owldesign mentioned it helped him) and it didn't cause the content to update correctly.

Obviously this isn't a "dealbreaker" or something that we cannot work around, but it is inconvenient, and takes extra time.

**Comment by benjamminf** [comment]
Is this an issue that's only recently happened? I made some changes to how content changes are detected about a month ago, this could be the root of the issue. I'm looking into it now.

**Comment by jake-dohm** [comment]
@benjamminf thanks for the uber-quick response 😀. I haven't experienced the problem before this past week. We haven't used NEO in a month or so though, so that timeline sounds about right.

**Comment by benjamminf** [comment]
@jake-dohm have you downloaded from the master branch? Just want to be sure it's the changes I made on the 3rd of Jan causing this. I can kind of replicate the problem, but it's only if I use shortcuts to change the field value and then save the entry, but only without releasing my finger off the command/control button.

**Comment by benjamminf** [comment]
Ah, okay so when using the context menu to modify the text, it happens if you don't then de-focus the input field. I'll bind it to a few more events to solve this problem.

**Comment by benjamminf** [comment]
Try pulling the `/neo/resources/` directory to see if that fixed the problem.

**Comment by jake-dohm** [comment]
Thanks, Ben, that seems to have fixed the issue! I'll report back if I have any more trouble.

**Comment by benjamminf** [comment]
Great :) I'll leave this open for now

**Comment by jake-dohm** [comment]
I just ran into the problem again 😬. I have downloaded the plugin and replaced the old plugin, and it's still not saving correctly.

I haven't noticed it but once, and it was when I removed a link from some text and then saved, it would re-appear linked once the entry saved.

**Comment by benjamminf** [comment]
Okay so you have a rich text field, and you remove a link and then save and it doesn't save?

**Comment by jake-dohm** [comment]
The entry will save, but the link will not be removed. It reverts back to it's original (linked state).

And, I found another text field, where I'll change a line of text it won't update either. Same as earlier.

**Comment by benjamminf** [comment]
Seems the observer is always a change behind. Hold up, adding in a execution cycle delay to see if this fixes it.

**Comment by benjamminf** [comment]
@jake-dohm Try pulling the same resources folder down now

**Comment by jake-dohm** [comment]
The resources folder from the master branch, correct?

**Comment by jake-dohm** [comment]
That seems to have fixed all of the problems I've been having!

I think you can go ahead and close the issue, I'll let you know if it comes back up.

Thanks so much @benjamminf!

**Comment by benjamminf** [comment]
Yay :man_dancing: all good, I'll close it for now
