### ISSUE TITLE
Dynamic Asset Folders

### ISSUE THREAD

**Issue by johnhoysa** [benjamminf/craft-neo#76]
Hi there, 

Great product, I am having one issue that I hope to get some assistance with:
The fields created with Neo do not seem to display all images in the assets folder for the entry upon creation of the Neo field when asset fields are dynamic.
 
New fields: Show what appears to be the last two items in our assets folder and one random other image.
If I create module-1 I am able to upload an item directly to that block with no problem. 
If I create module-2 I am not able to see the image used for module-1.

Once I save the entry: I am able to see images in my assets folder as expected.
So now I have module-1 and module-2.
If I go to add an image to module-2 I am able to see the image used in module-1. I am then able to add the image from module-1 to also be used in module-2.
If I create module-3 I once again do not see all the images in my folder. It is not till after I save the entry that module-3 displays the assets folder.

Expected Results:
Once I create a new block of content with Neo and go to my Assets field I expect to see all images related to that entry, even if used in other Neo fields on the same page.

Workaround 1:
Upload one image at a time as I create each Neo block. This is not ideal if needing to use the image in multiple places on a page. A very edge case I know.

Workaround 2:
Create all our Neo blocks and upload all images for page into Assets.
Once page reloads we are then able to see all the images.
Issue: if creating new fields not able to access images till we save entry again.

I hope I provided enough information for you. Neo has been a great tool for me and can't wait to see where you take it!

thanks,

John

**Comment by benjamminf** [comment]
Hey John, thanks for reporting. Can I get you to post your settings for the asset field? In case you haven't already seen this, there's [a caveat when using dynamic folders on asset fields in Neo blocks](https://github.com/benjamminf/craft-neo/wiki/8.-FAQ#why-do-asset-fields-with-slug-as-an-upload-location-break-on-neo-blocks), which may the cause of this behaviour.

**Comment by johnhoysa** [comment]
Thanks for the info! Wished I had seen that earlier when I was setting up the site. 
Once our dev server is back up I will plan on testing. 

Thanks again! 

John

**Comment by johnhoysa** [comment]
Hi there, 

I went and added {{ object is neoblock ? object.owner.slug : object.slug }} as my upload location. It was {owner.slug} 

I have not seen any changes in behavior of my asset fields, did I forget to do something? 
I cleared Craft CMS cache and I also ran an assets update just in case that would help. I even doubled checked that I updated the correct fields. 

Thanks and appreciate the help :)

John
![asset-field-settings](https://cloud.githubusercontent.com/assets/487851/23814378/ef3897fe-05a8-11e7-921c-bc4715566dac.png)

**Comment by martinherweg** [comment]
I have a similar problem. 
I have checked what might be the problem and and found out that matrix fields have a owner as you add them.

If you dump a Neo Field it has no owner as long as you haven't saved the entry, therefore the path of the Asset Field isn't correct and you can't see the images belonging to the entry.

**Comment by martinherweg** [comment]
I've done some changes to the Plugin which worked for my setup.
Maybe you could try it too @johnhoysa ?
You can find the forked repo here https://github.com/martinherweg/craft-neo

The Changes I made can be seen here: https://github.com/martinherweg/craft-neo/commit/d4691f5ebde483b1ec3383246c0b3087d115ed5c

I will test it a bit and then would be happy to submit a PR @benjamminf

**Comment by johnhoysa** [comment]
@martinherweg, Thanks for the suggestion, for some reason this is not helping me out after some testing. Once I create an entry I am still seeing calls to images that are not on the server or related to the entry. It is as if the images are cached somehow, see attached image.The below image is what it looks like after I add a neo block and then try to add an image to it. The images listed are not on the server, nor are they related to the entry.
![asset-screen-neo](https://user-images.githubusercontent.com/487851/28527567-86a62658-7050-11e7-8510-28ab3bc8d7bb.jpg)


I did try the following in my assets path:
{{object.owner.section.handle}}, {{object.owner.slug}}, {owner.slug} and  {{ object is neoblock ? object.owner.slug : object.slug }}.

This was tested on new entries and existing entries with same results. 

Am I missing a step after updating my assets path? I clear my local CraftCMS cache but not sure if that helps or not. 

Thanks for reaching out, it is greatly appreciated. 

John

**Comment by martinherweg** [comment]
Hi John,

nothing I'm aware of. I have the same Problem with "Ghost Images" when I create a new Entry.

I have that even when I save the Entry and add the Neo Field, but as soon as I add at least one neo Field with an asset it works as expected.

So for Clarification here is what is working for me:

1. Create Entry with Neo Field containing an asset Field and Upload a File (the File Viewer shows 2 Ghost Images for Me)
2. Save the Entry
3. Add another Neofield containing an asset Field (the File viewer now shows the File from Step 1)

Sorry if that is not working for you. If I find out what might be the Problem I will post it here.

Cheers,
Martin

**Comment by johnhoysa** [comment]
Hi Martin,

Yeah I need a way to remove those ghost images. Images upload fine but those darn ghost images are bugging me. 

Appreciate they help!

**Comment by benjamminf** [comment]
@martinherweg thanks for the fix 👍 

This behaviour with assets is the standard behaviour for asset fields, as far as I can see. The problem is when the asset path is dependent on properties of an entry, if the entry hasn't even been saved yet and those properties aren't filled out, Craft can't resolve the path. So it seems it puts those assets in a temporary directory, and when the entry is saved and those properties are available, it moves them to the actual directory.

Assets in a temporary directory are those "ghost" assets, which is why they disappear when you save the entry. If you upload an asset while editing an entry and then don't save the entry, they stay in that temporary directory indefinitely – that is, until you select them for a saved entry or clear your caches.

**Comment by martinherweg** [comment]
@benjamminf I tested in a current Project and it works for me with the described flow in my last post. 

I submitted a PR even I don't know if the implementation is the best way :)

Regarding the "Ghost" assets at least for me cache clearing isn't helping.

**Comment by zizther** [comment]
@martinherweg Did you manage to sort out how to clear the ghost images, cache clearing isn't working for me either

**Comment by martinherweg** [comment]
Nope, still having ghost Images if I uploaded images before the changes in my PR.

**Comment by johnhoysa** [comment]
Hi everyone, I am going to close the issue even though my ghost images are still appearing. I do think this is a Craft CMS issue and not a Neo issue. 

@martinherweg, thanks for taking a look into this issue, I greatly appreciate the help and your time.
