### ISSUE TITLE
1.4.1 update made entry content disappear

### ISSUE THREAD

**Issue by 23d1** [benjamminf/craft-neo#81]
It seems when I go in to edit entries after updating, some are blank—although the database content is still there (as the website renders the content correctly). I'm assuming that if I save the blank page it will break though. Any way to fix this, could it be a migration issue?

This seems related; spectrum color picker fields in a separate tab fails to load on those specific entries as well. When it does work (on some pages) everything works.

The pages not working are pages with product fields from Craft Commerce, creating a new entry with the content works, but would love to see a fix as there are quite a few large pages with tons of Neo fields to reproduce.

**Comment by benjamminf** [comment]
This is almost certainly an issue with that color picker field. Neo blocks are initialised with JS, so if a JS error is encountered, those blocks don't get initialised.

Can you post what errors are printing to the console?

**Comment by benjamminf** [comment]
Also, you are right in that resaving that entry with blank blocks will mean losing your content (if you don't have revisions enabled). But the content is still there, and by updating Neo it would have triggered a full DB backup so worst case would require you re-importing that DB backup.

**Comment by 23d1** [comment]
Gotcha, yeah it seems to be giving this error:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at o (main.js:13)
    at HTMLDivElement.<anonymous> (main.js:14)
    at Function.each (jquery-2.2.4.min.js:2)
    at n.fn.init.each (jquery-2.2.4.min.js:2)
    at n.constructor.updatePreview (main.js:14)
    at main.js:14
    at n.constructor.toggleExpansion (main.js:14)
    at n.constructor.init (main.js:13)
    at n.constructor.constructor (garnish.min.js:9)
    at n.constructor (garnish.min.js:9)
```

Strangely, it seems to be working on other pages that don't have Commerce Product fields (essentially entries fields) in the Neo field. That might not be the case though. Strange indeed.

**Comment by benjamminf** [comment]
Okay so it's definitely this JS error causing the missing content problem. Not much help for finding the offending line though. What browser and it's version are you running?

**Comment by benjamminf** [comment]
Also, can you try temporarily disabling the colour picker plugin and see if that fixes it?

**Comment by 23d1** [comment]
Chrome 56.0.2924.87 (latest) on OSX. Definitely JS error as some of the stuff renders on some pages, and breaks either on or after the first Neo block, but sometimes cycles through a couple before breaking.
Disabling spectrum gives me a Craft error;
```
Internal Server Error

Trying to get property of non-object
```

The JS errors are in various places, sometimes
```
Uncaught TypeError: Cannot read property 'length' of undefined > Input.js:34
    at o (Block.js:67)
    at HTMLDivElement.<anonymous> (Block.js:460)
    at Function.each (jquery-2.2.4.min.js?d=1483153161:2)
    at n.fn.init.each (jquery-2.2.4.min.js?d=1483153161:2)
    at n.constructor.updatePreview (Block.js:339)
    at Block.js:570
    at n.constructor.toggleExpansion (Block.js:611)
    at n.constructor.init (Block.js:149)
    at n.constructor.constructor (garnish.js:5735)
    at n.constructor (garnish.js:5735)
```
And sometimes at;
```
Uncaught TypeError: Cannot read property 'length' of undefined > Block.js:67
    at o (Block.js:67)
    at HTMLDivElement.<anonymous> (Block.js:460)
    at Function.each (jquery-2.2.4.min.js?d=1483153143:2)
    at n.fn.init.each (jquery-2.2.4.min.js?d=1483153143:2)
    at n.constructor.updatePreview (Block.js:339)
    at Block.js:570
    at n.constructor.toggleExpansion (Block.js:611)
    at n.constructor.init (Block.js:149)
    at n.constructor.constructor (garnish.js:5735)
    at n.constructor (garnish.js:5735)
```

There's an inbetween that just flashes, as well, that I managed to screen capture;
![image](https://cloud.githubusercontent.com/assets/2627617/22905188/443931aa-f1f4-11e6-810d-9ed578d3bdaa.png)

**Comment by 23d1** [comment]
It seems to have something to do with these pieces of code in Block.js and Input.js;

Block.js
```
function _limit(s, l=40)
{
	return s.length > l ? s.slice(0, l - 3) + '...' : s
}
...
```

Input.js
```
init(settings = {})
	{
		settings = Object.assign({}, _defaults, settings)
...
```

**Comment by benjamminf** [comment]
Thanks for the details! I've tried both Spectrum and Product fields and can't seem to trip it up. But thanks for narrowing it down, I think I see the problem! I've written up the fix for it and committed it to the master. Try re-downloading the plugin (from the master branch) and see if that fixes it.

**Comment by 23d1** [comment]
That seems to have done, it. Hold on, gonna test on another install. It seems that perhaps the issue was with entries where neo field blocks were rolled up (i.e. double-click the "title-bar").

**Comment by benjamminf** [comment]
Awesome. Yeah, the error was with generating the content summaries for collapsed blocks. The `_limit` function truncated the content, but was expecting a string to be passed. For some odd reason, at some point it was getting passed `undefined`, causing the issue in `_limit`.

**Comment by 23d1** [comment]
Awesome. Yeah, it seems to be fixed. Working across sites. 💯  Dope!

I do get this warning from time to time on big entries, which is just a warning as far as I can tell (haven't messed around with garnish at all—so not sure); 

![image](https://cloud.githubusercontent.com/assets/2627617/22905903/f612dc08-f1f6-11e6-8b29-e8802835f0d3.png)

**Comment by benjamminf** [comment]
Whoops, forgot to close, thanks for that. Glad it's all working!

That warning is nothing to worry about, see #50. I actually get asked about this pretty often, I might add it to the FAQ.
