### ISSUE TITLE
Is uncompressed JS available?

### ISSUE THREAD

**Issue by intoeetive** [benjamminf/craft-neo#83]
Hi Benjamin,

Could you by chance release uncomressed JS source for this plugin?

I need to make some modifications to Neo's JS functions (auto-populate some fields based on conditional checks) and having the main.js uncompressed and human-readable would make my life easier =)

Thank you for the wonderful job of building it!

**Comment by zachshallbetter** [comment]
Hey @intoeetive. The Javascript is located in the /src directory and is compiled with Webpack. After you download the repo, you can install the npm modules with the command `npm install`. Then you can use the command `webpack` to compile, or `webpack --watch` to watch for changes and compile automatically.
