### ISSUE TITLE
Printing matrix field inside a neo field?

### ISSUE THREAD

**Issue by delajed** [benjamminf/craft-neo#84]
I haven't had any luck printing a matrix field inside a neo field. No errors, just no values rendered.

See code below:

```twig
   {% for block in entry.contentBlock.level(1) %}
      {% switch block.type.handle %}
        {% case 'text' %}
          {{ block.headline }}
          {{ block.body }}
          {% for block in entry.testing %}
            {% if block.type == "testing" %}
              {{ block.one }}
            {% endif %}
          {% endfor %}
      {% endswitch %}
    {% endfor %}
```

Any advice on how to fix this? I'm basically going off both Craft's matrix guide, and the neo wiki w/ no luck.

**Comment by benjamminf** [comment]
Looks like you have a few issues. You're using the `block` variable for both the Neo field and the nested Matrix field. Try renaming the variable to something else. Also, you seem to be referencing the Matrix field on the `entry` variable, rather than the `block`. Try this:

```twig
{% for block in entry.contentBlock.level(1) %}
  {% switch block.type.handle %}
    {% case 'text' %}
      {{ block.headline }}
      {{ block.body }}
      {% for subBlock in block.testing %}
        {% if subBlock.type == "testing" %}
          {{ subBlock.one }}
        {% endif %}
      {% endfor %}
  {% endswitch %}
{% endfor %}
```
