### ISSUE TITLE
Show field handle in Field Layout view

### ISSUE THREAD

**Issue by maxwellhibbert** [benjamminf/craft-neo#85]
This is a great plugin!
It would be super handy if field handles could be shown or even copied to the clipboard from the Field Layout view (via the cog icon). The extra layer of Neo means getting the handle for each field is tedious if you can't remember them.

**Comment by benjamminf** [comment]
This plugin seems like something you'd like: https://github.com/mmikkel/CpFieldLinks-Craft

I don't think it supports Neo, however it would be a great plugin to support. I'll put it on my TODO list.

**Comment by maxwellhibbert** [comment]
Yeah, I installed that with the hope that Neo was supported  :)
But yeah, that's precisely what I'm after for Neo.
