### ISSUE TITLE
Deleting Elements that have a Neo Field (such as en Entry) does not fire `onBeforeDeleteElements`

### ISSUE THREAD

**Issue by tjdraper** [benjamminf/craft-neo#94]
My field type has it's own table and watches for `elements.onBeforeDeleteElements` to clean up any orphaned items when something like entries are deleted like so:

```
craft()->on('elements.onBeforeDeleteElements', function (Event $event) {
	// ...do stuff to delete rows in my table owned by the element being deleted
});
```

However, it seems that Neo does not fire the `elements.onBeforeDeleteElements` event when parent elements are deleted. Compare this to the behavior of Matrix: if my field is in a Matrix field and an entry (or other containing element) is deleted, an `onBeforeDeleteElements` event is fired off for each Matrix block which my field will pick up and be able to clean up any orphaned table rows (and other things).

For whatever it's worth I also experienced this with SuperTable: https://github.com/engram-design/SuperTable/issues/72#issuecomment-289161179

Here is the commit there that addressed this issue: https://github.com/engram-design/SuperTable/commit/6bfb059d2cffe42753b4569444d00681b59a3e1d

**Comment by benjamminf** [comment]
I've implemented this in the dev branch, working on a few more things before I make the next release.
