### ISSUE TITLE
Nested Content - Live Preview Not working

### ISSUE THREAD

**Issue by yohoGDES** [benjamminf/craft-neo#97]
I've been working with this issue for a while now and I have done as much research as I can to attempt to resolve this. Essentially I have a reasonable number of nested fields and they are not displaying in live preview but do in the live site. It may be how I'm setting up my templates but I would love some input here.

![screen shot 2017-04-06 at 10 14 12 am](https://cloud.githubusercontent.com/assets/867967/24758890/a8cf4362-1ab1-11e7-8ab2-d05000420a57.png)

Here is the setup of what I have in the admin: 
```
Page Content (Neo)
- Section (block type)
-- Column (block type)
--- Components (block type, contains basic fields)
-- Column (block type)
--- Components (block type, contains basic fields)
```

Here is the template code used to display the content: 
% Main Block Content %
```
{# Get background image for section if it is set #}
{% set background = block.children.type('backgroundImage').first() %}

{# Echo background image on section #}
<section class="section-block {{background ? 'section-block--has-bg'}}" {{ background ? 'style= background-image:url(' ~ siteUrl ~ background.backgroundImage.first().url() ~ ');'}}>
	<div class="section-block__inner">

		{# Get Columns #}
		{% set columns = block.children.type('column') %}
		{# If the layout has columns, check for length and output #}
		{% if columns|length %}
			{% set columnCount = 0 %}
			{% for column in columns %}
				{% set columnCount = columnCount + 1 %}
				    <div class="column column--{{columnCount}} ">
					{% for item in column.children %}
						{# Output column components #}
						{% switch item.type.handle %}
							{% case 'headline' %}
								{% include '_components/headline.html' %}
							{% case 'text' %}
								{{ item.bodyContent }}
							{% case 'button' %}
								{% include '_components/button.html' %}
							{% case 'callToAction' %}
								{% include '_components/cta-basic.html' %}
							{% case 'foregroundImage' %}
								{% include '_components/foreground-image.html' %}
						{% endswitch %}
					{% endfor %}
				    </div>
			{% endfor %}
		{% endif %}
</section>
```

So the final output works fine, but live preview doesn't? Is this a scope issue or a bug? Can you provide any help for resolving this?

Thanks!

**Comment by benjamminf** [comment]
As I've mentioned in other related issues, Live Preview is a huge pain in the ass and is very temperamental. I've gone to great lengths to have Neo support it properly (#21), but due to how LP works it's not always going to play nice.

I suspect it has to do with this line:
```twig
{% set columns = block.children.type('column') %}
```
It should be the case but it might be forcing a database query when filtering by block type. In that case, LP would be operating on the old content, which would explain why it doesn't update.

If you change it to a Twig-only alternative, then it should get LP working again:
```twig
{% set columns = [] %}
{% for childBlock in block.children if childBlock.type.handle == 'column' %}
    {% set columns = columns|merge([childBlock]) %}
{% endfor %}
```
Little more verbose but hey, what can you do.

Let me know if this fixes it.

**Comment by yohoGDES** [comment]
@benjamminf Thank you for the quick reply. 

This does in fact make the content able to display in live preview (odd right?)... but it displays a duplicate of the first object in the grouping. 

The output is like this: 
```
Array: ["Craft\\Neo_BlockModel: "]
Column 1
Array: ["Craft\\Neo_BlockModel: ","Craft\\Neo_BlockModel: "]
Column 1 Column 2
```

With this code as the source: 
```
{% set columns = [] %}
{% for childBlock in block.children if childBlock.type.handle == 'column' %}
	{% set columns = columns|merge([childBlock]) %}
	{{ columns | inspect }}
	{% for column in columns %}
		{% set columnCount = columnCount + 1 %}
		Column {{ columnCount }}
	{% endfor %}
{% endfor %}
```

Any ideas on what could be causing that? I've included the count variable only as a means to show what and how many columns are being displayed. 

Essentially this is happening because of the way LP and Craft communicate and it makes a DB call which either fails and displays nothing or stops? 

Thanks again for your help with this.

**Comment by benjamminf** [comment]
You just need to replace that one line (`{% set columns = block.children.type('column') %}`) with what I wrote. The problem is you're looping over the columns twice, but one of them is inside the other. So you'll end up outputting the same column multiple times.

**Comment by benjamminf** [comment]
I've found the issue that's causing this in Neo and have fixed it. It'll be available in the next release, so when you upgrade next you can safely revert back to your old template code.

**Comment by yohoGDES** [comment]
Fantastic! Thank you @benjamminf
